# Generated by Django 4.1.5 on 2023-01-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_number', models.IntegerField()),
                ('Second_number', models.IntegerField()),
                ('Operation', models.CharField(max_length=1)),
                ('Result', models.IntegerField()),
                ('Created_on', models.DateField()),
            ],
        ),
    ]
