# Generated by Django 4.1.5 on 2023-01-04 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_operation_first_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='Second_number',
            new_name='second_number',
        ),
        migrations.AlterField(
            model_name='operation',
            name='Created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 15, 8, 59, 18074, tzinfo=datetime.timezone.utc)),
        ),
    ]
